<?php
/**
 * Created by PhpStorm.
 * User: kristhian
 * Date: 12/22/14
 * Time: 1:13 AM
 */


echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";
echo "INSERT INTO curso_disponible (id_curso_disponible, id_socio_tecnologico, folio_socio_tecnologico, nombre_curso, descripcion, pdf_temario, id_cat_curso, horas_curso, formato, fecha_inicio, estatus_curso, id_cat_comprobante, persona_creacion, fecha_creacion, persona_modificacion, fecha_modificacion, activo) VALUES (NULL, '3', '2323', 'subarda', 'cuvezon', '', '1', '34', 'presencial', '2014-12-02', NULL, '2', '4', '2014-12-22 07:30:48', '4', '2014-12-22 07:30:48', '1');";